name: Checks

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/checks.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/checks.yml'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Install dependencies
        run: pnpm install

      - name: Run format check
        run: pnpm format:check

      - name: Run light build of universe/client
        run: pnpm client build:light
