name: Release

on:
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Create and publish versions
        id: changesets
        uses: changesets/action@master
        with:
          version: pnpm changeset version
          commit: 'chore: 🤖 update versions'
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for a universe/client version
        uses: actions/github-script@v5
        id: get-client-version
        with:
          script: console.log(process.env.DATA)
        env:
          DATA: ${{ steps.changesets.outputs.publishedPackages }}
